CREATE TABLE USERS (
    ID SERIAL NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    FACEBOOK_ID VARCHAR(255),
    GOOGLE_ID VARCHAR(255),
    APPLE_ID VARCHAR(255),
    VERIFY_STATUS VARCHAR(255) NOT NULL,
    USER_LEVEL VARCHAR(255) NOT NULL,
    PROFILE_IMG VARCHAR(255),
    CREATED_DT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_DT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE shop_food (
    ID SERIAL NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    PROFILE_IMG VARCHAR(255) NOT NULL,
    COVER_IMG VARCHAR(255) NOT NULL,
    CATEGORY_TAGS VARCHAR[] NOT NULL,
    RATING DOUBLE,
    LOC_LAT DOUBLE NOT NULL,
    LOC_LONG DOUBLE NOT NULL,
    LOC_DETAIL VARCHAR(255) NOT NULL,
    OPERATION_HOURS VARCHAR[],
    TEL VARCHAR(14) NOT NULL,
    VARIFY_STATUS VARCHAR(255) NOT NULL,
    CREATED_DT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_DT TIMESTAMP NOT NULL DEFAULT NOW()
);